/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaisOuvidasRouteImport } from './routes/mais-ouvidas'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as IndexRouteImport } from './routes/index'

const MaisOuvidasRoute = MaisOuvidasRouteImport.update({
  id: '/mais-ouvidas',
  path: '/mais-ouvidas',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/mais-ouvidas': typeof MaisOuvidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/mais-ouvidas': typeof MaisOuvidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/mais-ouvidas': typeof MaisOuvidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loja' | '/mais-ouvidas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loja' | '/mais-ouvidas'
  id: '__root__' | '/' | '/loja' | '/mais-ouvidas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojaRoute: typeof LojaRoute
  MaisOuvidasRoute: typeof MaisOuvidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mais-ouvidas': {
      id: '/mais-ouvidas'
      path: '/mais-ouvidas'
      fullPath: '/mais-ouvidas'
      preLoaderRoute: typeof MaisOuvidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojaRoute: LojaRoute,
  MaisOuvidasRoute: MaisOuvidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
